"""fix stripe webhook sync

Revision ID: 039e819f2706
Revises: 6ada1fc3b20f
Create Date: 2026-05-07 15:14:09.714292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039e819f2706'
down_revision: Union[str, None] = '6ada1fc3b20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
